site_name: 我的文档
nav:
- 目录: '目录.md'
- 芯片架构: '芯片架构.md'
- 编程语言: '编程语言.md'
- 编译器: '编译器.md'
- 构建工具: '构建工具.md'
- 操作系统: '操作系统.md'
- 物理层协议: '物理层协议.md'
- 逆向: '逆向.md'
- 单片机: '单片机.md'
- 操作系统: '操作系统.md'
- 关于: '关于.md'
theme: readthedocs